name: multiscale
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pillow
  - requests
  - pyimagej
  - cython
  - h5py
  - jupyter
  - pandas
  - scipy
  - pytest
  - ipywidgets
  - conda-forge::simpleitk
  - vs2015_runtime
  - pip
  - pip:
    - tifffile